### ISSUE TITLE
tN PDF: Pandoc Issues

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/sysadmin#28]
_From @jag3773 on July 20, 2015 14:20_

Fix pandoc to support images, or fix pandoc-dev list spacing.  Possibly just install 1.15 from https://github.com/jgm/pandoc/releases.

_Copied from original issue: unfoldingWord-dev/tools#99_

**Comment by jag3773** [comment]
_From @greenpotatochip on July 22, 2015 15:33_

installed pandoc 1.15 on test.door43.org and 2015 texlive in /usr/local/texlive/2015/bin/x86_64-linux
added 
pathmunge /usr/local/texlive/2015/bin/x86_64-linux
to /etc/profile

**Comment by jag3773** [comment]
If this is working correctly then we'll want to update the puppet recipe to do what you have done here.

**Comment by jag3773** [comment]
_From @greenpotatochip on July 24, 2015 13:18_

The only reports I have so far is that it's working, and seems to be working better than the one on prod. I'm not sure if it fixed whatever issue prompted the update to begin with though? I hope to get some puppet updates done this weekend.

**Comment by jag3773** [comment]
_From @phillip-hopper on July 24, 2015 15:16_

My experience is that Pandoc 1.15 will include images from URL's, but 1.12 only would include images using the local file system.

**Comment by jag3773** [comment]
_From @richmahn on July 25, 2015 1:46_

So, should I try removing the code in the shell script that strips out the image tags and see if it works?

**Comment by jag3773** [comment]
_From @richmahn on July 25, 2015 1:47_

What else does this fix? I don't know what the "ulem" issue is...does it deal with this upgrade?

**Comment by jag3773** [comment]
_From @phillip-hopper on July 25, 2015 13:36_

I don't know about the "ulem" issue, but the [release notes are here.](http://pandoc.org/releases.html)

The markdown format for embedded images starts with an exclamation mark, 
```
![description goes here](https://door43.org/_media/some/location/imagename.png)
```

**Comment by jag3773** [comment]
_From @greenpotatochip on July 25, 2015 18:43_

pandoc and texlive have been upgraded on us.door43.org (prod).
The full install of texlive says it included ulem, so that issue may be solved too. 
They should be in your path. Please let me know of any issues.

**Comment by jag3773** [comment]
_From @greenpotatochip on August 15, 2015 2:25_

Notes on Pandoc / Texlive install 
I'm still pondering how to get this into puppet, but I figured I should document it here.

```
------ pandoc install -------

1. sudo yum install haskell-platform
2. As a normal user with sudo priv, run
	cabal update
   The scripts invoke sudo when they need it 
3. Then edit ~/.cabal/config file (a default file should exist there)	
   Note "--" is a comment in this file
   The three lines that are modified from the default are:
	user-install: False
	root-cmd: sudo
	prefix: /usr/local  (under the GLOBAL SECTION)
4. As the same normal user, run
   	cabal install pandoc pandoc-citeproc --dry-run -v    (this tests the config)
   If that looks good, run it w/o the "--dry-run -v"
	cabal install pandoc pandoc-citeproc

And then wait while it builds and installs everything. This generates
many many warnings. It should put pandoc in /usr/local/bin/

------------ texlive install --------------

followed this: http://www.tug.org/texlive/quickinstall.html
using this source: http://www.tug.org/texlive/acquire-netinstall.html

wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar xvfz install-tl-unx.tar.gz 
cd install-tl-20150724/
sudo ./install-tl (installs 4+GB of files)
(this has a ncurses menu for configuration options )

# add this to /etc/profile
pathmunge /usr/local/texlive/2015/bin/x86_64-linux
```

**Comment by jag3773** [comment]
_From @dsm-git on August 16, 2015 0:32_

Please add a wiki page for this in the Door43 repo.

**Comment by jag3773** [comment]
_From @greenpotatochip on August 16, 2015 3:19_

Can you point me to a link to do that?

**Comment by jag3773** [comment]
_From @phillip-hopper on August 16, 2015 23:6_

@greenpotatochip: https://github.com/unfoldingWord-dev/Door43/wiki

**Comment by greenpotatochip** [comment]
closed with commits 299e62 (added module) and 56e10e (enabled for test and prod)
