### ISSUE TITLE
Need Abyssinica SIL font installed on door43.org through puppet

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/sysadmin#34]
Needing a font installed with puppet for door43.org and test.door43.org. It is the Abyssinica SIL font. Can get the latest here:

http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=abyssinicasil_download

**Comment by richmahn** [comment]
Or can get the font from the zip file here.
[AbyssinicaSIL-1.500-web.zip | uploaded via ZenHub](https://files.zenhub.io/55fb439bfd7194de615a664e)

**Comment by greenpotatochip** [comment]
fixed with commit 6a31d71
