### ISSUE TITLE
As an App Admin, I want a production Gogs Instance on the git server so that I can migrate DokuWiki content to it.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/sysadmin#37]
Acceptance Criteria:
* [x] - It has nginx, postgress and gogs available
* [x] - I can ssh to it on port 22
* [x] - I can access it from the web on 80 and 443

**Comment by jag3773** [comment]
still need to:

* [ ] setup replication for gogs-repositories and gogs-attachments.  Maybe just sync all of git home dir?
* [ ] Review postgres replication to make sure it's functioning properly
* [ ] Standup mirror on `mon` server and make sure everything is syncing properly
* [ ] Review whether we only want 443 or if we want to support non-SSL also
