### ISSUE TITLE
As as an App Admin, I want all DokuWiki user accounts moved to Gogs to support migration.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/sysadmin#39]
Acceptance Criteria:
1 - I can use code at github.com/gogits/gogs/pull/2070/commits
2 - Users can access Gogs without registering.
3 - DokuWiki accounts remain until Door43 looks to Gogs

**Comment by jag3773** [comment]
Possibly, we could set DokuWiki to query the Gogs user DB via the postgres DB.  Not sure if it is worth the development effort though.

**Comment by bspidel** [comment]
This issue was moved to unfoldingWord-dev/gogs#10
