### ISSUE TITLE
As an App Admin, I want gitolite content moved to Gogs to support migration

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/sysadmin#40]
Acceptance Criteria:
1 - I can see gitolite repo sync to Gogs

**Comment by jag3773** [comment]
@richmahn I think the procedure for this should be:

1. Check to see if user with UUID exists, if not, create it (via API)
2. Check to see if repo exists for user, if not, create it (via API)
3. Get the remote location from the repo (either https or ssh, whatever is easier)
4. Push to the remote location from the gitolite repo

The Gogs API is documented at https://github.com/gogits/go-gogs-client/wiki .

Every tS "user" in gitolite (which is really the device UUID) will end up with their own account in Gogs.  No person will have access to these, they will strictly be mirrors of what's pushed to gitolite.

In a future version of tS, users will be able to claim their previous work by cloning/forking from the UUID user repo into their own account.

**Comment by jag3773** [comment]
@richmahn Extra step to add to the git hook:

* [ ] Add `\s5` and `\p` markers to beginning of each chunk *if they don't exist*

**Comment by richmahn** [comment]
Do we still need this step @jag3773? Every chunk is in its own file, so would have to go through each file and add \s5 \p to it.

**Comment by jag3773** [comment]
We can pass on that for now
