### ISSUE TITLE
As an App Admin, I want DokuWiki content moved to Gogs to minimize manual effort.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/sysadmin#41]
Acceptance Criteria:
1. - I can see structure as user/lang-project
2. - All dokuwiki markup is converted to gogs markdown

**Comment by jag3773** [comment]
@richmahn Do we have a script somewhere that can convert our DW syntax to MarkDown format?  I'd like to try getting an OBS project moved over to see if it will look as we expect.

**Comment by jag3773** [comment]
Couple notes, we'll need to split the monolithic language repos into their language-project counterparts.  The following links give information on how to do that while maintaining the version history:
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/
http://blogs.atlassian.com/2014/04/tear-apart-repository-git-way/

**Comment by jag3773** [comment]
I think we'll want to take the following as our procedure for the move:

* [ ] Split out project from language, as in comment above
* [ ] Push/Create the repo in git.door43.org following the `lang-project` nomenclature
* [ ] Convert to MarkDown (possibly create a tag for this commit as something like "md" ?)

The advantage of doing it this way is that we'll have all the previous revision history using the DW syntax and then we'll have a single commit for the switch to MarkDown.

For resources that are published already, like en-obs, I'd also like to create a tag with the currently published version (v 4 in this case).  That will help facilitate change log creation later on down the road.

**Comment by bspidel** [comment]
This issue was moved to unfoldingWord-dev/gogs#11
