### ISSUE TITLE
Puppet not Completing on uk

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/sysadmin#50]
Puppet is not completing on the uk server.  Please check out the errors and fix them in the manifests.

**Comment by jpetitt1** [comment]
/var/lib/puppet/reports/ shows errors/failures for php55w and others.  The webtatic repo has not been added.  Should php be updated?

Also, I noticed that updates were added on Wed Mar 23rd...  Did the errors start afterwards?
